public class Studentdetails {
    public void NameOfSudent(){
        string myName = ('Aydin');
        system.debug('My name is: '+ myName);

        string PoB = ('Baku');
        system.debug('Place of birth: '+ PoB);

        string TyL = ('Exploring,Eating,sleeping');
        system.debug('Things you like: '+ TyL);

        string PyLv = ('Afganistan, North Korea');
        system.debug('Places you like to visit: '+ PyLv);

    }
    
}
